mode = "dark"
accent = "#ff6b1a"
selection = "#34302a"
muted = "#5d625e"
background = "#0e0f10"
dark_background = "#0b0c0d"
darker_background = "#080909"
lighter_background = "#191b1c"
foreground = "#d4d7d2"
dark_foreground = "#7e8580"
light_foreground = "#e1e4df"
bright_foreground = "#f1f3ed"
red = "#e5484d"
yellow = "#d7b866"
orange = "#ff6b1a"
green = "#91ad85"
cyan = "#80b6b2"
blue = "#8ba4bb"
magenta = "#b29cb8"
brown = "#987455"
bright_red = "#ff7478"
bright_yellow = "#edcf8a"
bright_green = "#b1cc9e"
bright_cyan = "#a5d1c9"
bright_blue = "#acc4d6"
bright_magenta = "#d1b6d2"
